import React from "react";

const paths = {
  Aatrox: require("./championImages/Aatrox.png"),
  Amumu: require("./championImages/Amumu.png"),
  Annie: require("./championImages/Annie.png"),
  Ashe: require("./championImages/Ashe.png"),
  Azir: require("./championImages/Azir.png"),
  Brand: require("./championImages/Brand.png"),
  Braum: require("./championImages/Braum.png"),
  Diana: require("./championImages/Diana.png"),
  DrMundo: require("./championImages/DrMundo.png"),
  Ezreal: require("./championImages/Ezreal.png"),
  Ivern: require("./championImages/Ivern.png"),
  Janna: require("./championImages/Janna.png"),
  Jax: require("./championImages/Jax.png"),
  Khazix: require("./championImages/Khazix.png"),
  Kindred: require("./championImages/Kindred.png"),
  KogMaw: require("./championImages/KogMaw.png"),
  LeBlanc: require("./championImages/LeBlanc.png"),
  Lucian: require("./championImages/Lucian.png"),
  Lux: require("./championImages/Lux.png"),
  Malphite: require("./championImages/Malphite.png"),
  Malzahar: require("./championImages/Malzahar.png"),
  Maokai: require("./championImages/Maokai.png"),
  MasterYi: require("./championImages/MasterYi.png"),
  Nami: require("./championImages/Nami.png"),
  Nasus: require("./championImages/Nasus.png"),
  Nautilus: require("./championImages/Nautilus.png"),
  Neeko: require("./championImages/Neeko.png"),
  Nocturne: require("./championImages/Nocturne.png"),
  Olaf: require("./championImages/Olaf.png"),
  Ornn: require("./championImages/Ornn.png"),
  Qiyana: require("./championImages/Qiyana.png"),
  RekSai: require("./championImages/RekSai.png"),
  Renekton: require("./championImages/Renekton.png"),
  Senna: require("./championImages/Senna.png"),
  Singed: require("./championImages/Singed.png"),
  Sion: require("./championImages/Sion.png"),
  Sivir: require("./championImages/Sivir.png"),
  Skarner: require("./championImages/Skarner.png"),
  Soraka: require("./championImages/Soraka.png"),
  Syndra: require("./championImages/Syndra.png"),
  Taliyah: require("./championImages/Taliyah.png"),
  Taric: require("./championImages/Taric.png"),
  Thresh: require("./championImages/Thresh.png"),
  Twitch: require("./championImages/Twitch.png"),
  Varus: require("./championImages/Varus.png"),
  Vayne: require("./championImages/Vayne.png"),
  Veigar: require("./championImages/Veigar.png"),
  Vladimir: require("./championImages/Vladimir.png"),
  Volibear: require("./championImages/Volibear.png"),
  Warwick: require("./championImages/Warwick.png"),
  Yasuo: require("./championImages/Yasuo.png"),
  Yorick: require("./championImages/Yorick.png"),
  Zed: require("./championImages/Zed.png"),
  Zyra: require("./championImages/Zyra.png")
};

function ChampionImage(props) {
  return <img src={paths[props.champion]} alt={props.champion} />;
}

export default ChampionImage;
